name: country
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  flutter_calendar_carousel: ^2.0.1
  flutter_credit_card: ^2.0.0
  http:
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_pdfview: ^1.0.4
  path_provider: ^2.0.2
  photo_view: ^0.11.1
  provider: ^5.0.0
  sentry_flutter: ^5.1.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.7
  video_player: ^2.1.9
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/miniatura.png"
  adaptive_icon_background: "assets/icons/miniatura.png"

flutter:


  uses-material-design: true


  assets:
    - assets/backgrounds/
    - assets/icons/
    - assets/images/
    - assets/reglamento/reglamento.pdf

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
        - asset: assets/fonts/Montserrat-Light.otf
        - asset: assets/fonts/Montserrat-Regular.otf
        

